config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  root to: 'homes#top'
  get "home/about" => "homes#about" , as: "about"

  resources :books
  resources :users, onry:[:show, :index, :new, :create, :edit, :update]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
 belongs_to :user
 
 validates :title, presence: true
 validates :body,  presence: true, length: { maximum: 200 }
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  
  belongs_to :user
  attachment :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
  attachment :profile_image
  
 validates :name,  presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 } 
 validates :introduction,  length: { maximum: 50 }
 
 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
  
  def after_inactive_sign_up_path_for(resource)
    users_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, {only:[:edit, :update, :destroy]}

  def new
    @book=Book.new
  end

  def create
    @user=current_user
    @book=Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book)
    else
    @books=Book.all
    render :index
    end
  end

  def index
    @book=Book.new
    @books=Book.all
    @user = current_user

  end

  def show
   @book_new = Book.new
   @book = Book.find(params[:id])
   @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book.id)
    else
    render :edit
    end
  end


  def destroy
    @book=Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def ensure_correct_user
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
     redirect_to books_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  
  def new
      @post_image=PostImage.new
  end

  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    @post_image.save
    redirect_to post_images_path  
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :baria_user, only: [:edit,:update]
  
  def index
    @book=Book.new
    @users=User.all
    @user = current_user
 
  end

  def show
  
    @user = User.find(params[:id])
    @book=Book.new
    @books=@user.books
    
  end

  def edit
    @user = User.find(current_user.id)
    @users=User.all
  end
  
  def new
    @book=Book.new
  end
 
  def create
    @books=Book.all
    @book=Book.new(book_params)
     @book.user_id = current_user.id 
    if @book.save
    flash[:notice] = "You have created book successfully."
    redirect_to books_path(@book.id)
    else
    render :show
    end  
  end
  
def update
   @user=User.find(params[:id])
   if @user.update(user_params)
    flash[:notice] = "You have updated user successfully."
   redirect_to user_path(@user.id)
   else
   render :edit
   end
end
  
  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image, :image_id, )
  end
  
  protect_from_forgery with: :null_session
  
   def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<main>
 <p id="notice"></p>
  <div class="container">
   <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

<h1>Editing Book</h1>

 <% if @book.errors.any? %>
 <%= @book.errors.count %>件のerrorが発生しました
 <% @book.errors.full_messages.each do |message| %>
 <%= message %>
 <% end %>
 <% end %>
 
<%= form_with model:@book, local:true do |f| %>
  <div><label for="inputName">Title</label><br>
  <%= f.text_field :title, autofocus: true, id:"inputTitle", placeholder:"Title"%></div>

  <div><label for="inputOpinion">Opinion</label><br>
  <%= f.text_area :body, autofocus: true, id:"inputopinion" %></div>

  <%= f.submit "Update Book",class: "btn btn-success"  %>
<% end %>
   <%= link_to "Show", book_path(@book) %>
   <%= link_to "Back", books_path %>
   </div>
  </div>
 </div>
</main>

app/views/books/index.html.erb
<main>
 <% if @book.errors.any? %>
 <%= @book.errors.count %>件のエラーが発生しました
 <% @book.errors.full_messages.each do |message| %>
 <%= message %>
 <% end %>
 <% end %>
 
 <p id="notice"></p>
 <div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", size:'100x100' %>
      <table class="table">
        <tbody>
         <tr>
          <th>name</th>
	         <th><%= @user.name %></th>
         </tr>
          <tr>
          <th>introduction</th>
	         <th><%= @user.introduction %></th>
          </tr>
         </tbody>
       </table>
<div class="row">
 <%= link_to "", edit_user_path(@user),class:"btn btn-outline-secondary btn-block fas fa-user-cog edit_user"%>
</div>


<h2 class="mt-3">New book</h2>

<%= form_with model: @book, local:true do |f| %>
 <h4>Title</h4>
  <%= f.text_field :title %></br>
 <h4>Opinion</h4>
  <%= f.text_area :body %>
 <%= f.submit "Create Book", class: "btn btn-success col-xs-12" %>
  <% end %>
</div>

<div class="col-md-8 offset-md-1">
 <h2>Books</h2>
 <table class="table table-hover table-inverse">
  <thead>
   <tr>
    <th colspan="1"></th>
    <th>Title</th>
    <th>Opinion</th>
   </tr>
  </thead>

  <tbody>
  <% @books.each do |book| %>
   <tr>
    <th><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %></th>
             <% end %>
    <th><%= link_to book_path(book) do %>
          <%= book.title %>
             <% end %>
    </th>
    <th><%= book.body %></th>
   </tr>
  <% end %>
  </tbody>
</table>
</div>
</main>


<!--<h1>New book</h1>
<%# if @book.errors.any? %>
  <%#= @book.errors.count %>件のエラーが発生しました
  <%# @book.errors.full_messages.each do |message| %>
    <%#= message %>
  <%# end %>
<%# end %>

<%#=form_with model:@book,local:true do |f| %>

<h4>Title</h4>
  <%#= f.text_field :title %>

<h4>Opinion</h4>
  <%#= f.text_area :body %>

  <%#= f.submit 'Create Book' %>

<%# end %>-->

app/views/books/show.html.erb
<main>
 <%= flash[:notice] %>
 <div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", size:'100x100' %>
      <table class="table">
        <tbody>
         <tr>
          <th>name</th>
	         <th><%= @user.name %></th>
         </tr>
          <tr>
          <th>introduction</th>
	         <th><%= @user.introduction %></th>
          </tr>
         </tbody>
       </table>
<div class="row">
  <%= link_to "", edit_user_path(@user),class:"btn btn-outline-secondary btn-block fas fa-user-cog edit_user"%>
</div>


<h2 class="mt-3">New book</h2>
 <% if @book_new.errors.any? %>
 <%= @book_new.errors.count %>件のエラーが発生しました
 <% @book_new.errors.full_messages.each do |message| %>
 <%= message %>
 <% end %>
 <% end %>


<%= form_with model: @book_new, local:true do |f| %>
 <h4>Title</h4>
  <%= f.text_field :title %></br>
 <h4>Opinion</h4>
  <%= f.text_area :body %>
 <%= f.submit "Create Book", class: "btn btn-success col-xs-12" %>
  <% end %>
</div>


<div class="col-md-8 offset-md-1">
 <h2>Book detail</h2>
 <table class="table table-hover table-inverse">
  <tbody>
   <tr>
    <td><%= link_to user_path(@user) do %>
          <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %><br>
    <%= @user.name %>
    </td>
             <% end %>
    <td><%= link_to book_path(@book) do %>
          <%= @book.title %>
             <% end %>
    </td>
    <td><%= @book.body %></td>
    <% if @user.id == current_user.id %>
    <td><%= link_to "Edit", edit_book_path(@book),class:"btn btn-sm btn-success"%></td>
    <td><%= link_to "Destroy", book_path(@book), method: :delete,class:"btn btn-sm btn-danger"%></td>
   <% end %>
   </tr>
  </tbody>
</table>
</div>
</main>

app/views/homes/about.html.erb
<main>
        <p id="notice"></p>
        <div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>
      </main>

  

app/views/homes/top.html.erb
<main>
<p id="notice"></p>
 <div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
         <%= link_to "Log in", new_user_session_path,class:"btn btn-info btn-sm btn-block mb-3 sign_in"%>
        </div>
        <div class="row">
         <%= link_to "Sign Up", new_user_registration_path,class:"btn btn-success btn-sm btn-block sign_up"%>
        </div>
      </div>
    </div>
  </div>
</div>
</main>

app/views/layouts/_notification.html.erb
<div class="Notification">
 <% flash.each do |key, value| %>
 <%= content_tag :div, value, class: key %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if user_signed_in? %>
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/">Bookers</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <%= link_to "Home", user_path(current_user),class:"fas fa-home nav-link text-light"%>
          <%= link_to "Users", users_path,class:"fas fa-users nav-link text-light"%>
          <%= link_to "Books", books_path,class:"fas fa-book-open nav-link text-light"%>
          <%= link_to "Logout", destroy_user_session_path, method: :delete,class:"fas fa-sign-out-alt nav-link text-light"%>
        </ul>
      </div>
    </div>
  </nav>
</header>

    <% else %>
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
           <%= link_to "Home", root_path,class:"fas fa-home nav-link text-light"%>
           <%= link_to "About", about_path,class:"fas fa-link nav-link text-light"%>
           <%= link_to "sign up", new_user_registration_path,class:"fas fa-user-plus nav-link text-light"%>
           <%= link_to "login", new_user_session_path,class:"fas fa-sign-in-alt nav-link text-light"%>
        </ul>
      </div>
    </div>
  </nav>
</header>
  <% end %>

 <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>

 <%= yield %>

 <footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
   </div>
  </footer>
 </body>
</html>

app/views/post_images/new.html.erb
<h1>画像投稿フォーム</h1>
<%= form_with model: @post_image, local:true do |f| %>
  <h4>画像</h4>
  <%= f.attachment_field :image %>

  <%= f.submit '投稿' %>
<% end %>



<!--<h1>New book</h1>
#<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<%=form_with model:@book,local:true do |f| %>

<h4>Title</h4>
  <%= f.text_field :title %>

<h4>Opinion</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book' %>
 
<% end %>


<h1>Users</h1>

<table>
 <thead>
  <tr>
   <th>image</th>
   <th>name</th>
   <th calspan="3"></th>
  </tr>
 </thead>

  <tbody>
 # <% @books.each do |book| %>
   <tr>
    <td><%=  %></td>
    <td><%=  %></td>
   </tr>
  <% end %>
  </tbody>
</table>

</main>

<footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer> -->




show コピー分　↓


<h1>New book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<%=form_with model:@book,local:true do |f| %>

<h4>Title</h4>
  <%= f.text_field :title %>

<h4>Opinion</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book' %>
 
<% end %>


<h1>Books</h1>

<table>
 <thead>
  <tr>
   <th>Title</th>
   <th>Opinion</th>
  </tr>
 </thead>

  <tbody>
  <% @books.each do |book| %>
   <tr>
    <td><%= book.title %></td>
    <td><%= book.body %></td>
   </tr>
  <% end %>
  </tbody>
</table>

</main>

<footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/users/edit.html.erb
<main>
  <div class="container">
   <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

<h2>User info</h2>
 <% if @user.errors.any? %>
 <%= @user.errors.count %>件のエラーが発生しました
 <% @user.errors.full_messages.each do |message| %>
 <%= message %>
 <% end %>
 <% end %>

<%= form_with model:@user, local:true do |f| %>
  <div><label for="inputName">Name</label><br>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%></div>

  <div><label for="inputImage">Image</label><br>
  <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>  </div>

  <div><label for="user_introduction">Introduction</label><br>
  <%= f.text_area :introduction, autofocus: true, id:"inputintroduction" %></div>

  <%= f.submit "Update User",class: "btn btn-secondary" %>
<% end %>

 </div>
</main>

app/views/users/index.html.erb
<main>
 <p id="notice"></p>
 <div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", size:'100x100' %>
      <table class="table">
        <tbody>
         <tr>
          <th>name</th>
	         <th><%= @user.name %></th>
         </tr>
          <tr>
          <th>introduction</th>
	         <th><%= @user.introduction %></th>
          </tr>
         </tbody>
       </table>
<div class="row">
   <%= link_to "", edit_user_path(@user),class:"btn btn-outline-secondary btn-block fas fa-user-cog edit_user"%>
</div>

      
<h2 class="mt-3">New book</h2>
 <% if @book.errors.any? %>
 <%= @book.errors.count %>件のエラーが発生しました
 <% @book.errors.full_messages.each do |message| %>
 <%= message %>
 <% end %>
 <% end %>

<%= form_with model: @book, local:true do |f| %>
 <h4>Title</h4>
  <%= f.text_field :title %></br>
 <h4>Opinion</h4>
  <%= f.text_area :body %>
 <%= f.submit "Create Book", class: "btn btn-success col-xs-12" %>
 <% end %>
</div>


<div class="col-md-8 offset-md-1">
 <h2>Users</h2>
 <table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td> <%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %></td>
        <td><%= user.name %></td>
        <td><%= link_to "Show", user_path(user) %></td>
      </tr>
    <% end %>
   </tbody>
  </table>
 </div>
</main>

app/views/users/show.html.erb
<main>
 <%= flash[:notice] %>
 <div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
       <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", size:'100x100' %>
      <table class="table">
        <tbody>
         <tr>
          <th>name</th>
	         <th><%= @user.name %></th>
         </tr>
          <tr>
          <th>introduction</th>
	         <th><%= @user.introduction %></th>
          </tr>
         </tbody>
       </table>
<div class="row">
  <%= link_to "", edit_user_path(@user),class:"btn btn-outline-secondary btn-block fas fa-user-cog edit_user"%>
</div>


<h2 class="mt-3">New book</h2>


<%= form_with model: @book, local:true do |f| %>
 <h4>Title</h4>
  <%= f.text_field :title %></br>
 <h4>Opinion</h4>
  <%= f.text_area :body %>
 <%= f.submit "Create Book", class: "btn btn-success col-xs-12" %>
  <% end %>
</div>

<div class="col-md-8 offset-md-1">
 <h2>Books</h2>
 <table class="table table-hover table-inverse">
  <thead>
   <tr>
    <th colspan="1"></th>
    <th>Title</th>
    <th>Opinion</th>
   </tr>
  </thead>

  <tbody>
  <% @books.each do |book| %>
   <tr>
    <th><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %></th>
             <% end %>
    <th><%= link_to book_path(book) do %>
          <%= book.title %>
             <% end %>
    </th>
    <th><%= book.body %></th>
   </tr>
  <% end %>
  </tbody>
</table>
</div>
</main>